name: Django Deploy CD
on:
  push:
    branches: [main]
    paths:
      - backend/**
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy to server
      # don't run locally
        if: "!contains(github.event.head_commit.message, 'ci skip')"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.REMOTE_HOST }}
          username: ${{ vars.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_PEM_KEY }}
          port: ${{ vars.REMOTE_PORT }}
          working-directory: backend
          script: |
            cd /home/ubuntu/gpt-project
            git pull ${{secrets.REPO_URL}}
            sudo systemctl stop gunicorn
            cd /home/ubuntu/gpt-project/backend
            source ./ENV/bin/activate
            pip install -r ./requirements.txt --upgrade
            deactivate
            sudo systemctl start gunicorn